---
name: Howard integration workflow

on:
  pull_request:
    types:
      - opened
      - closed
      - synchronize

jobs:
  markdown-check:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-markdown-check.yml@main

  yaml-check:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-yaml-check.yml@main
    with:
      config-file-path: '.yamllint.yml'

  repo-standard:
    uses:
      ai-cfia/github-workflows/.github/workflows/workflow-repo-standards-validation.yml@main
    secrets: inherit
